---
title             : "EDLD 610 Final Project"
shorttitle        : "Exploring Trends in Major League Sports "

author: 
  - name          : "Woocheol Kim"
    affiliation   : "1"
    corresponding : yes   
    address       : "1208 University St, Eugene, OR 97403"
    email         : "wkim4@uoregon.edu"
  - name          : "Jessica Canfield"
    affiliation   : "1"
    corresponding : no   
    address       : "1208 University St, Eugene, OR 97403"
    email         : "jcanfiel@uoregon.edu"

affiliation:
  - id            : "1"
    institution   : "University of Oregon"

authornote: |
  Jessica Canfield & Woocheol Kim are both Marketing PhD students at the University of Oregon.

abstract: |
  One or two sentences providing a **basic introduction** to the field,  comprehensible to a scientist in any discipline.
  
  Two to three sentences of **more detailed background**, comprehensible  to scientists in related disciplines.
  
  One sentence clearly stating the **general problem** being addressed by  this particular study.
  
  One sentence summarizing the main result (with the words "**here we show**" or their equivalent).
  
  Two or three sentences explaining what the **main result** reveals in direct comparison to what was thought to be the case previously, or how the  main result adds to previous knowledge.
  
  One or two sentences to put the results into a more **general context**.
  
  Two or three sentences to provide a **broader perspective**, readily comprehensible to a scientist in any discipline.
  
  <!-- https://tinyurl.com/ybremelq -->
  
keywords          : "sports, NBA, NHL, NFL, MLB"
wordcount         : "X"

bibliography      : ["r-references.bib"]

floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : no

documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_pdf
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      warning = FALSE,
                      message = FALSE)

library(papaja)
library(kableExtra)
library(dplyr)
library(here)
library(rio)
library(tidyverse)
library(janitor)
library(stats)
library(knitr)
library(tidyr)

```

```{r import data}
mlb <- import(here("Data", "MLB.xlsx")) %>%
  characterize() %>%  
  clean_names() %>% 
  select(sport, team, year, capacity, attend_tot, attend_avg, games, ticket_price, home_wins) %>% 
  as_tibble()

mlb <- mlb %>% mutate(capacity = numeric(capacity))

is.character(mlb$capacity) 
```

```{r}
nba <- import(here("Data", "NBA.xlsx")) %>%
  characterize() %>%  
  clean_names()%>% 
  select(sport, team, year, capacity, attend_tot, attend_avg, games, ticket_price, home_win)%>% 
  as_tibble() %>% 
  rename(home_wins = home_win) %>% 
  as_tibble()

ncaaf <- import(here("Data", "NCAAF.xlsx")) %>%
  characterize() %>%  
  clean_names() %>% 
  select(sport, team, year, capacity, attend_tot, attend_avg, games, ticket_price, home_wins) %>% 
  as_tibble()

nfl <- import(here("Data", "NFL.xlsx")) %>%
  characterize() %>%  
  clean_names()%>% 
  select(sport, team, year, capacity, attend_tot, attend_avg, games, ticket_price, home_wins) %>% 
  as_tibble()

nhl <- import(here("Data", "NHL.xlsx")) %>%
  characterize() %>%  
  clean_names()%>% 
  select(sport, team, year, capacity, attend_tot, attend_avg, games, ticket_price, home_wins) %>% 
  as_tibble() 


sports <- bind_rows(mlb, nba, ncaaf, nfl, nhl) %>% as_tibble()

```


# Methods
We report how we determined our sample size, all data exclusions (if any), all manipulations, and all measures in the study. <!-- 21-word solution (Simmons, Nelson & Simonsohn, 2012; retrieved from http://ssrn.com/abstract=2160588) -->

## Participants

## Material

## Procedure

## Data analysis
We used `r cite_r("r-references.bib")` for all our analyses.


# Results

# Discussion


\newpage

# References
```{r create_r-references}
r_refs(file = "r-references.bib")
```

\begingroup
\setlength{\parindent}{-0.5in}
\setlength{\leftskip}{0.5in}

<div id = "refs"></div>
\endgroup
